version: "3"

services:
  loadbalancer:
    image: bitnami/java:latest
    ports:
      - "8800:8800"
    environment:
      - SERVER_PORT=8800
    volumes:
      - ./target/load-balancer-1.0-SNAPSHOT.jar:/loadbalancer.jar
    command: "java -cp /loadbalancer.jar xyz.rganvir.LoadBalancer"
  backend1:
    image: bitnami/java:latest
    ports:
      - "8801:8801"
    environment:
      - SERVER_PORT=8801
    volumes:
      - ./target/load-balancer-1.0-SNAPSHOT.jar:/loadbalancer.jar
    command: "java -cp /loadbalancer.jar xyz.rganvir.BackendServer"
