version: "3.8"

services:
  loadbalancer:
    extends:
      file: java-service.yaml
      service: java_app
    ports:
      - "8800:8800"
    environment:
      JVM_OPTS: >
        -DSERVER_PORT=8800
        -DNTHREADS=20
        -DVTHREADS=true
      TARGET_CLASS: xyz.rganvir.LoadBalancerMain
  backend1:
    extends:
      file: java-service.yaml
      service: java_app
    ports:
      - "8801:8801"
    environment:
      JVM_OPTS: >
        -DSERVER_PORT=8801
        -DNTHREADS=5
      TARGET_CLASS: xyz.rganvir.BackendServer
  backend2:
    extends:
      file: java-service.yaml
      service: java_app
    ports:
      - "8802:8801"
    environment:
      JVM_OPTS: >
        -DSERVER_PORT=8801
        -DNTHREADS=5
      TARGET_CLASS: xyz.rganvir.BackendServer
  backend3:
    extends:
      file: java-service.yaml
      service: java_app
    ports:
      - "8803:8801"
    environment:
      JVM_OPTS: >
        -DSERVER_PORT=8801
        -DNTHREADS=5
      TARGET_CLASS: xyz.rganvir.BackendServer
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    container_name: otel-collector
    ports:
      - "4318:4318"
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
    command: ["--config=/etc/otelcol-config.yml"]
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: admin
        DOCKER_INFLUXDB_INIT_PASSWORD: admin
        DOCKER_INFLUXDB_INIT_ORG: AnOrganization
        DOCKER_INFLUXDB_INIT_BUCKET: a-bucket
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: a-token
  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
