services:
  java_app:
    image: bitnami/java:20.0.2-10
    environment:
      CLASSPATH: /loadbalancer.jar
    volumes:
      - ../target/libs:/jars
    command: sh -c "java --enable-preview -cp '/jars/*' $$JAVA_OPTS $$TARGET_CLASS"